"""
actions/templates/email.py
===========================
Email templates used by office.py for sending and replying.
"""

REPLY_TEMPLATES = [
    "Thank you for your message. I have reviewed the information and will follow up shortly.",
    "Noted. I will look into this and get back to you by end of day.",
    "Thank you for the update. Everything looks good from my side.",
    "Received. I will coordinate with the team and revert back to you.",
    "Thanks for reaching out. I have forwarded this to the relevant department.",
    "Good morning. I have reviewed your email and the matter is being handled.",
    "Thank you. I will review the attached documents and respond accordingly.",
    "Appreciated. I will circle back to you after the team meeting.",
    "Message received. I will escalate this to the appropriate team.",
    "Thank you for flagging this. We will investigate and revert.",
]

SEND_TEMPLATES = [
    {"subject": "Daily status update",
     "body": "Hi team,\n\nHere is today's status update. All tasks are on track and no blockers at this time.\n\nPlease let me know if you need any further details.",
     "attach": True},
    {"subject": "Meeting reminder",
     "body": "Hi,\n\nJust a reminder that we have our weekly sync scheduled. Please ensure you have reviewed the agenda beforehand.\n\nLooking forward to seeing everyone.",
     "attach": False},
    {"subject": "Project update — Q2",
     "body": "Hi,\n\nI wanted to share a quick update on the Q2 project milestones. We are currently on schedule and all deliverables are being tracked.\n\nI will send a detailed report by end of week.",
     "attach": True},
    {"subject": "Action items from today's meeting",
     "body": "Hi team,\n\nPlease find below the action items from today's meeting:\n1. Review the deployment checklist\n2. Update the risk register\n3. Confirm stakeholder sign-off\n\nKindly complete these by Friday.",
     "attach": True},
    {"subject": "System maintenance notice",
     "body": "Hi,\n\nPlease be advised that scheduled maintenance will take place this weekend. Services may be unavailable during this window.\n\nKindly save your work and log off before the maintenance begins.",
     "attach": False},
    {"subject": "Request for document review",
     "body": "Hi,\n\nCould you please review the attached document and provide your feedback by end of week? Your input is important for the final submission.\n\nThank you for your time.",
     "attach": True},
    {"subject": "Weekly report",
     "body": "Hi,\n\nPlease find the weekly report attached. Key highlights:\n- All KPIs are within acceptable range\n- Two minor issues were resolved\n- One item remains open and is being tracked\n\nPlease review and revert with any comments.",
     "attach": True},
    {"subject": "Follow-up on previous discussion",
     "body": "Hi,\n\nI wanted to follow up on our previous discussion regarding the infrastructure upgrade. Could you please confirm the timeline so we can plan accordingly?\n\nLooking forward to your response.",
     "attach": False},
    {"subject": "New policy update",
     "body": "Hi team,\n\nPlease be informed of the updated IT security policy effective from next month. All staff are required to review and acknowledge the document.\n\nKindly confirm receipt of this email.",
     "attach": True},
    {"subject": "Invitation: Team lunch",
     "body": "Hi everyone,\n\nYou are invited to the team lunch this Friday. Please confirm your attendance by Wednesday so we can make the necessary arrangements.\n\nLooking forward to a great time together.",
     "attach": False},
    {"subject": "Budget approval request",
     "body": "Hi,\n\nI am writing to request approval for the Q3 budget allocation as discussed in our last meeting. The breakdown has been shared in the attached document.\n\nKindly review and approve at your earliest convenience.",
     "attach": True},
    {"subject": "Incident report — resolved",
     "body": "Hi,\n\nPlease be informed that the reported incident has been resolved. Root cause analysis is complete and preventive measures have been implemented.\n\nA detailed report will be circulated by end of day.",
     "attach": True},
    {"subject": "Training session reminder",
     "body": "Hi,\n\nThis is a reminder that the mandatory security awareness training session is scheduled for next week. Please ensure you have registered and blocked your calendar.\n\nAttendance is compulsory for all staff.",
     "attach": False},
    {"subject": "Access request",
     "body": "Hi,\n\nI would like to request access to the shared network folder for the ongoing project. Please let me know what approvals are required.\n\nThank you for your assistance.",
     "attach": False},
    {"subject": "End of day wrap-up",
     "body": "Hi,\n\nJust a quick end-of-day wrap-up:\n- Completed all assigned tasks\n- Attended two meetings\n- Pending items have been documented and will be addressed tomorrow\n\nHave a good evening.",
     "attach": False},
    {"subject": "Onboarding checklist",
     "body": "Hi,\n\nPlease find the onboarding checklist for the new team member. Kindly ensure all items are completed within the first week.\n\nLet me know if you have any questions.",
     "attach": True},
    {"subject": "Server monitoring alert — resolved",
     "body": "Hi team,\n\nThe earlier monitoring alert has been investigated and resolved. It was a false positive triggered by a scheduled backup job.\n\nNo further action is required.",
     "attach": False},
    {"subject": "Quarterly review preparation",
     "body": "Hi,\n\nAs we approach the end of the quarter, please start preparing your individual reports for the quarterly review. The template has been shared on the shared drive.\n\nDeadline for submission is end of next week.",
     "attach": True},
    {"subject": "Password expiry reminder",
     "body": "Hi,\n\nThis is a reminder that your network password will expire in 7 days. Please update it before expiry to avoid being locked out.\n\nContact the helpdesk if you require assistance.",
     "attach": False},
    {"subject": "Confirmation of receipt",
     "body": "Hi,\n\nThis email is to confirm receipt of your recent submission. We will review it and get back to you within 3 business days.\n\nThank you for your patience.",
     "attach": False},
]